import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import AttendanceCamera from '../components/AttendanceCamera';
import AttendanceDetailModal from '../components/AttendanceDetailModal';
import attendanceService from '../services/attendanceService';
import authService from '../services/authService';
import { 
  Calendar as CalendarIcon, 
  TrendingUp, 
  Users, 
  Clock, 
  CheckCircle2, 
  AlertCircle,
  ArrowUpRight,
  MoreVertical
} from 'lucide-react';
import Calendar from '../components/Calendar/Calendar';
import { formatDateKey } from '../components/Calendar/useCalendar';

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [attendanceMap, setAttendanceMap] = useState({});
  const [selectedLogDate, setSelectedLogDate] = useState(null);
  const [isLogModalOpen, setIsLogModalOpen] = useState(false);
  const [filterDate, setFilterDate] = useState({
    month: (new Date().getMonth() + 1).toString(),
    year: new Date().getFullYear().toString()
  });
  const navigate = useNavigate();

  const fetchAttendance = async () => {
    const currentUser = authService.getCurrentUser();
    if (!currentUser) return;

    try {
      const { month, year } = filterDate;
      const response = await attendanceService.getAttendanceByUserId(
        currentUser._id, 
        { month, year }
      );
      if (response.success && response.data) {
        const mappedData = {};
        response.data.forEach(record => {
          mappedData[record.date] = record;
        });

        // Add auto-absent records for past days in the selected month
        const now = new Date();
        const yearInt = parseInt(year);
        const monthInt = parseInt(month);
        const daysInMonth = new Date(yearInt, monthInt, 0).getDate();
        
        let lastDayToCheck = daysInMonth;
        if (yearInt === now.getFullYear() && monthInt === (now.getMonth() + 1)) {
          lastDayToCheck = now.getDate() - 1;
        } else if (new Date(yearInt, monthInt - 1) > now) {
          lastDayToCheck = 0;
        }

        for (let d = 1; d <= lastDayToCheck; d++) {
          const dk = `${yearInt}-${monthInt.toString().padStart(2, '0')}-${d.toString().padStart(2, '0')}`;
          if (!mappedData[dk]) {
            mappedData[dk] = { status: 'absent', date: dk, autoGenerated: true };
          }
        }

        setAttendanceMap(mappedData);
      }
    } catch (err) {
      console.error('Attendance fetch error:', err);
    }
  };

  useEffect(() => {
    const currentUser = authService.getCurrentUser();
    if (!currentUser) {
      navigate('/login');
    } else {
      setUser(currentUser);
      fetchAttendance();
    }
  }, [navigate, filterDate]);

  // Automated Absence & Summary Logic
  const getSummary = () => {
    let presentCount = 0;
    let absentCount = 0;
    
    const now = new Date();
    const currentYear = parseInt(filterDate.year);
    const currentMonth = parseInt(filterDate.month);
    
    // Calculate total days in the selected month
    const daysInMonth = new Date(currentYear, currentMonth, 0).getDate();
    
    // Determine how many days have passed relative to the current date
    let lastDayToCheck = daysInMonth;
    if (currentYear === now.getFullYear() && currentMonth === (now.getMonth() + 1)) {
      // If we are in the current month, only check up to yesterday for auto-absences
      lastDayToCheck = now.getDate() - 1; 
    } else if (new Date(currentYear, currentMonth - 1) > now) {
      // If we are in the future, don't count any days
      lastDayToCheck = 0;
    }

    for (let day = 1; day <= daysInMonth; day++) {
      const dateKey = `${currentYear}-${currentMonth.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
      const record = attendanceMap[dateKey];

      if (record) {
        if (record.status === 'present') presentCount++;
        else if (record.status === 'absent') absentCount++;
      } else if (day <= lastDayToCheck) {
        // Automatically count missing past records as absent
        absentCount++;
      }
    }

    return { present: presentCount, absent: absentCount };
  };

  const { present, absent } = getSummary();
  const todayKey = formatDateKey(new Date());
  const isAlreadyMarked = !!attendanceMap[todayKey];

  const handleDateSelect = (date) => {
    const dateKey = formatDateKey(date);
    setSelectedLogDate(dateKey);
    setIsLogModalOpen(true);
  };

  if (!user) return null;

  const stats = [
    {
      title: 'Monthly Present',
      value: present,
      icon: CheckCircle2,
      color: 'bg-green-500',
      trend: '+12%',
      trendUp: true
    },
    {
      title: 'Monthly Absent',
      value: absent,
      icon: AlertCircle,
      color: 'bg-red-500',
      trend: '-5%',
      trendUp: false
    },
  ];

  return (
    <div className="space-y-10 animate-in fade-in slide-in-from-bottom-6 duration-1000">

      {/* Header with Welcome Message */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-3">
             <span className="px-3 py-1 bg-blue-100 text-blue-700 text-[10px] font-black uppercase tracking-widest rounded-full">
                Personnel Portal
             </span>
             <span className="text-slate-300 text-xs font-bold font-mono">/ dashboard</span>
          </div>
          <h1 className="text-5xl font-black text-slate-900 tracking-tighter">
            Welcome, <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">{user.name.split(' ')[0]}</span>
          </h1>
          <p className="text-slate-500 font-medium text-lg max-w-xl">
            You've maintained an <span className="text-slate-900 font-bold">88% presence rate</span> this month. Keep it up!
          </p>
        </div>

        <div className="bg-white p-2 rounded-2xl shadow-xl shadow-slate-200/40 border border-slate-100 flex items-center gap-4">
           <div className="w-12 h-12 bg-slate-50 rounded-xl flex items-center justify-center">
              <CalendarIcon className="h-6 w-6 text-slate-400" />
           </div>
           <div className="pr-6">
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Active Session</p>
              <p className="text-sm font-black text-slate-900">
                 {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              </p>
           </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {stats.map((stat, i) => (
          <div
            key={stat.title}
            className="group relative bg-white p-8 rounded-[2.5rem] border border-slate-100 shadow-2xl shadow-slate-200/50 hover:shadow-blue-500/10 transition-all duration-500 overflow-hidden"
          >
            <div className={`absolute top-0 right-0 w-32 h-32 ${stat.color.replace('bg-', 'bg-')} rounded-full -mr-16 -mt-16 opacity-30 group-hover:scale-110 transition-transform duration-700`}></div>

            <div className="flex justify-between items-start relative z-10">
              <div className={`${stat.color.replace('bg-', 'bg-')} p-4 rounded-2xl transition-transform group-hover:rotate-6`}>
                <stat.icon className={`h-7 w-7 ${stat.color.replace('bg-', 'text-')}`} />
              </div>
              <div className={`flex items-center gap-1 ${stat.trendUp ? 'text-green-500' : 'text-rose-500'} text-xs font-black`}>
                <TrendingUp className="h-3 w-3" />
                {stat.trend}
              </div>
            </div>

            <div className="mt-8 relative z-10">
              <p className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-2">{stat.title}</p>
              <div className="flex items-end justify-between">
                <h3 className="text-4xl font-black text-slate-900 tracking-tighter">{stat.value}</h3>
                <div className="h-2 w-24 bg-slate-100 rounded-full overflow-hidden">
                   <div className={`h-full ${stat.color} w-3/4 animate-in slide-in-from-left duration-1000`}></div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Main Action Area */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
        {/* Attendance Portal */}
        <div className="lg:col-span-5 space-y-8">
          <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-[0_20px_50px_rgba(0,0,0,0.03)] relative overflow-hidden group">
            {/* Filter UI */}
            <div className="flex items-center justify-between mb-8">
               <h2 className="text-xl font-black text-slate-800 tracking-tight">Biometric Terminal</h2>
               <div className="flex items-center gap-2">
                  <select
                    value={filterDate.month}
                    onChange={(e) => setFilterDate(prev => ({ ...prev, month: e.target.value }))}
                    className="bg-slate-50 border-none rounded-lg text-xs font-bold p-2 outline-none focus:ring-2 ring-blue-500/20"
                  >
                    {Array.from({ length: 12 }, (_, i) => (
                      <option key={i + 1} value={i + 1}>
                        {new Date(0, i).toLocaleString('en-US', { month: 'short' })}
                      </option>
                    ))}
                  </select>
                  <select
                    value={filterDate.year}
                    onChange={(e) => setFilterDate(prev => ({ ...prev, year: e.target.value }))}
                    className="bg-slate-50 border-none rounded-lg text-xs font-bold p-2 outline-none focus:ring-2 ring-blue-500/20"
                  >
                     <option value="2025">2025</option>
                     <option value="2026">2026</option>
                  </select>
               </div>
            </div>

            {isAlreadyMarked ? (
              <div className="py-12 flex flex-col items-center justify-center text-center space-y-6 animate-in fade-in zoom-in duration-500">
                <div className="w-24 h-24 bg-green-50 rounded-[2.5rem] flex items-center justify-center border border-green-100">
                  <CheckCircle2 className="h-10 w-10 text-green-500" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-slate-900 text-xl font-black tracking-tight">Today Logged!</h3>
                  <p className="text-slate-400 text-sm font-medium">Your biometric verification is complete. See you tomorrow!</p>
                </div>
              </div>
            ) : (
              <AttendanceCamera onSuccess={fetchAttendance} />
            )}
          </div>
        </div>

        {/* Records & Activity */}
        <div className="lg:col-span-7 space-y-6">
          <div className="bg-white rounded-[3rem] border border-slate-100 shadow-2xl shadow-slate-200/60 overflow-hidden min-h-[500px] relative">
            <div className="p-8 border-b border-slate-50 flex justify-between items-center bg-slate-50/40 sticky top-0 backdrop-blur-md z-10">
              <div className="flex items-center gap-3">
                 <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                    <ArrowUpRight className="h-4 w-4 text-white" />
                 </div>
                 <h3 className="font-black text-slate-900 tracking-tight">Real-time Logs</h3>
              </div>
              <button className="p-2 border border-slate-200 rounded-xl hover:bg-slate-50 transition-colors">
                 <MoreVertical className="h-4 w-4 text-slate-400" />
              </button>
            </div>
            
            <div className="p-4 sm:p-6 transition-all duration-700">
               <Calendar 
                attendanceData={attendanceMap} 
                onDateSelect={handleDateSelect}
               />
            </div>
          </div>
        </div>

        {/* Detail Modal */}
        <AttendanceDetailModal 
          isOpen={isLogModalOpen}
          onClose={() => setIsLogModalOpen(false)}
          date={selectedLogDate}
          record={attendanceMap[selectedLogDate]}
        />

      </div>
    </div>
  );
};

export default Dashboard;
