import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import BiometricTerminal from '../components/BiometricTerminal';
import AttendanceDetailModal from '../components/AttendanceDetailModal';
import attendanceService from '../services/attendanceService';
import authService from '../services/authService';
import { 
  Calendar as CalendarIcon, 
  TrendingUp, 
  Users, 
  Clock, 
  CheckCircle2, 
  AlertCircle,
  ArrowUpRight,
  ShieldCheck,
  LogOut,
  MoreVertical
} from 'lucide-react';
import Calendar from '../components/Calendar/Calendar';
import { formatDateKey } from '../components/Calendar/useCalendar';

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [attendanceMap, setAttendanceMap] = useState({});
  const [selectedLogDate, setSelectedLogDate] = useState(null);
  const [isLogModalOpen, setIsLogModalOpen] = useState(false);
  const [filterDate, setFilterDate] = useState({
    month: (new Date().getMonth() + 1).toString(),
    year: new Date().getFullYear().toString()
  });
  const navigate = useNavigate();

  const fetchAttendance = async () => {
    const currentUser = authService.getCurrentUser();
    if (!currentUser) return;

    try {
      const { month, year } = filterDate;
      const response = await attendanceService.getAttendanceByUserId(
        currentUser._id, 
        { month, year }
      );
      if (response.success && response.data) {
        const mappedData = {};
        response.data.forEach(record => {
          mappedData[record.date] = record;
        });

        // Add auto-absent records for past days in the selected month
        const now = new Date();
        const yearInt = parseInt(year);
        const monthInt = parseInt(month);
        const daysInMonth = new Date(yearInt, monthInt, 0).getDate();
        
        let lastDayToCheck = daysInMonth;
        if (yearInt === now.getFullYear() && monthInt === (now.getMonth() + 1)) {
          lastDayToCheck = now.getDate() - 1;
        } else if (new Date(yearInt, monthInt - 1) > now) {
          lastDayToCheck = 0;
        }

        for (let d = 1; d <= lastDayToCheck; d++) {
          const dk = `${yearInt}-${monthInt.toString().padStart(2, '0')}-${d.toString().padStart(2, '0')}`;
          if (!mappedData[dk]) {
            mappedData[dk] = { status: 'absent', date: dk, autoGenerated: true };
          }
        }

        setAttendanceMap(mappedData);
      }
    } catch (err) {
      console.error('Attendance fetch error:', err);
    }
  };

  useEffect(() => {
    const currentUser = authService.getCurrentUser();
    if (!currentUser) {
      navigate('/login');
    } else {
      setUser(currentUser);
      fetchAttendance();
    }
  }, [navigate, filterDate]);

  // Automated Absence & Summary Logic
  const getSummary = () => {
    let presentCount = 0;
    let absentCount = 0;
    
    const now = new Date();
    const currentYear = parseInt(filterDate.year);
    const currentMonth = parseInt(filterDate.month);
    
    // Calculate total days in the selected month
    const daysInMonth = new Date(currentYear, currentMonth, 0).getDate();
    
    // Determine how many days have passed relative to the current date
    let lastDayToCheck = daysInMonth;
    if (currentYear === now.getFullYear() && currentMonth === (now.getMonth() + 1)) {
      // If we are in the current month, only check up to yesterday for auto-absences
      lastDayToCheck = now.getDate() - 1; 
    } else if (new Date(currentYear, currentMonth - 1) > now) {
      // If we are in the future, don't count any days
      lastDayToCheck = 0;
    }

    for (let day = 1; day <= daysInMonth; day++) {
      const dateKey = `${currentYear}-${currentMonth.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
      const record = attendanceMap[dateKey];

      if (record) {
        if (record.status === 'present') presentCount++;
        else if (record.status === 'absent') absentCount++;
      } else if (day <= lastDayToCheck) {
        // Automatically count missing past records as absent
        absentCount++;
      }
    }

    return { present: presentCount, absent: absentCount };
  };

  const { present, absent } = getSummary();
  const todayKey = formatDateKey(new Date());
  
  const todayLog = attendanceMap[todayKey];
  const isCheckedIn = !!todayLog;
  const isCheckedOut = !!(todayLog?.checkOut?.time || todayLog?.checkoutTime);

  const handleDateSelect = (date) => {
    const dateKey = formatDateKey(date);
    setSelectedLogDate(dateKey);
    setIsLogModalOpen(true);
  };

  if (!user) return null;

  const stats = [
    {
      title: 'Monthly Present',
      value: present,
      icon: CheckCircle2,
      color: 'bg-green-500',
      trend: '+12%',
      trendUp: true
    },
    {
      title: 'Monthly Absent',
      value: absent,
      icon: AlertCircle,
      color: 'bg-red-500',
      trend: '-5%',
      trendUp: false
    },
  ];

  // --- Analytics Calculation ---
  const parseDuration = (str) => {
    if (!str || str === 'In Progress') return 0;
    const parts = str.split(' ');
    let mins = 0;
    parts.forEach(p => {
      if (p.includes('h')) mins += parseInt(p) * 60;
      if (p.includes('m')) mins += parseInt(p);
    });
    return mins;
  };

  const formatMins = (totalMins) => {
    const h = Math.floor(totalMins / 60);
    const m = totalMins % 60;
    return `${h}h ${m}m`;
  };

  const todayStats = {
    hours: todayLog?.totalHours || '0h 0m',
    earning: todayLog?.earning || 0
  };

  const monthlyStats = Object.values(attendanceMap).reduce((acc, curr) => {
    acc.totalMins += parseDuration(curr.totalHours || curr.workingHours);
    acc.totalEarning += (curr.earning || 0);
    return acc;
  }, { totalMins: 0, totalEarning: 0 });

  return (
    <div className="space-y-10 animate-in fade-in duration-700">
      {/* Welcome & Quick Analytics Section */}
      <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6">
        <div>
          <h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em] mb-2">Workspace Overview</h2>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight">
            Welcome back, <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">{user.name.split(' ')[0]}!</span>
          </h1>
          <p className="text-slate-500 font-medium mt-1">Here's a summary of your activity for {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        </div>

        <div className="flex items-center gap-3 bg-white p-1.5 rounded-2xl border border-slate-100 shadow-sm self-start lg:self-auto">
          <div className="px-4 py-2.5 bg-slate-50 rounded-xl text-center min-w-[120px]">
             <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1.5">Session Date</p>
             <p className="text-sm font-black text-slate-800 tabular-nums">{todayKey}</p>
          </div>
        </div>
      </div>

      {/* Main Grid: Terminal & Stats */}
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-8">
        
        {/* Left/Main Column: Biometric Terminal */}
        <div className="xl:col-span-12">
          <div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-[0_20px_50px_rgba(0,0,0,0.02)] overflow-hidden">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              {/* Terminal View */}
              <div className="p-8 lg:p-12 border-b lg:border-b-0 lg:border-r border-slate-50">
                <div className="flex items-center justify-between mb-8">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center">
                      <ShieldCheck className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="font-black text-slate-900 tracking-tight">Biometric Terminal</h3>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none">Security Status: Active</p>
                    </div>
                  </div>
                  <div className="px-3 py-1 bg-green-50 text-green-600 text-[10px] font-bold uppercase tracking-widest rounded-full border border-green-100 animate-pulse">
                    Online
                  </div>
                </div>

                {!isCheckedIn ? (
                  <BiometricTerminal mode="checkin" onSuccess={fetchAttendance} />
                ) : !isCheckedOut ? (
                  <BiometricTerminal mode="checkout" onSuccess={fetchAttendance} />
                ) : (
                  <div className="bg-slate-50/50 rounded-[2rem] p-12 flex flex-col items-center text-center space-y-6 border border-dashed border-slate-200">
                    <div className="w-20 h-20 bg-green-500 rounded-full flex items-center justify-center shadow-lg shadow-green-200">
                       <CheckCircle2 className="h-10 w-10 text-white" />
                    </div>
                    <div className="space-y-2">
                      <h2 className="text-2xl font-black text-slate-900 tracking-tight">Shift Complete</h2>
                      <p className="text-slate-500 font-medium text-sm max-w-[280px]">Your identity has been verified. Daily attendance logs are synchronized.</p>
                    </div>
                  </div>
                )}
              </div>

              {/* Real-time Insights & Stats */}
              <div className="p-8 lg:p-12 bg-slate-50/30 flex flex-col justify-between">
                <div>
                  <h3 className="font-black text-slate-900 tracking-tight mb-8">Daily Insights</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-4">
                      <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center">
                        <Clock className="h-6 w-6" />
                      </div>
                      <div>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Today's Hours</p>
                        <p className="text-xl font-black text-slate-900">{todayStats.hours}</p>
                      </div>
                    </div>
                    <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex items-center gap-4">
                      <div className="w-12 h-12 bg-green-50 text-green-600 rounded-xl flex items-center justify-center font-black text-xl">₹</div>
                      <div>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Today's Pay</p>
                        <p className="text-xl font-black text-slate-900">₹{todayStats.earning}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-8 space-y-4">
                  <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-3xl p-8 text-white shadow-xl relative overflow-hidden group">
                    <div className="relative z-10 flex items-center justify-between">
                      <div>
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Monthly Valuation</p>
                        <p className="text-3xl font-black tracking-tight">₹{monthlyStats.totalEarning}</p>
                        <p className="text-xs font-bold text-slate-500 mt-1 uppercase tracking-widest">Gross Earning Estimate</p>
                      </div>
                      <div className="w-14 h-14 bg-white/10 rounded-2xl flex items-center justify-center">
                        <ArrowUpRight className="h-6 w-6" />
                      </div>
                    </div>
                    <div className="absolute -right-10 -bottom-10 w-40 h-40 bg-blue-500/10 rounded-full blur-3xl group-hover:bg-blue-500/20 transition-all"></div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                     {stats.map(stat => (
                       <div key={stat.title} className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm">
                          <div className="flex items-center gap-2 mb-3">
                             <stat.icon className={`h-3.5 w-3.5 ${stat.color.replace('bg-', 'text-')}`} />
                             <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{stat.title.split(' ')[1]} Status</span>
                          </div>
                          <div className="flex items-end justify-between">
                             <p className="text-2xl font-black text-slate-900">{stat.value}</p>
                             <div className={`px-2 py-0.5 rounded-lg text-[9px] font-black ${stat.trendUp ? 'bg-green-50 text-green-600' : 'bg-rose-50 text-rose-600'}`}>
                                {stat.trend}
                             </div>
                          </div>
                       </div>
                     ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* History Log Column */}
        <div className="xl:col-span-12">
          <div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-[0_20px_50px_rgba(0,0,0,0.02)] overflow-hidden">
            <div className="p-8 border-b border-slate-50 flex flex-col sm:flex-row justify-between items-center gap-4">
              <div className="flex items-center gap-3">
                 <div className="w-10 h-10 bg-slate-900 text-white rounded-xl flex items-center justify-center">
                    <CalendarIcon className="h-5 w-5" />
                 </div>
                 <div>
                    <h3 className="font-black text-slate-900 tracking-tight">Attendance Logs</h3>
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none">Monthly History</p>
                 </div>
              </div>
              <div className="flex items-center gap-2 bg-slate-50 p-1.5 rounded-xl border border-slate-100">
                  <select
                    value={filterDate.month}
                    onChange={(e) => setFilterDate(prev => ({ ...prev, month: e.target.value }))}
                    className="bg-white border-none rounded-lg text-[10px] font-black uppercase p-2 outline-none focus:ring-2 ring-blue-500/20 cursor-pointer"
                  >
                    {Array.from({ length: 12 }, (_, i) => (
                      <option key={i + 1} value={i + 1}>
                        {new Date(0, i).toLocaleString('en-US', { month: 'short' })}
                      </option>
                    ))}
                  </select>
                  <select
                    value={filterDate.year}
                    onChange={(e) => setFilterDate(prev => ({ ...prev, year: e.target.value }))}
                    className="bg-white border-none rounded-lg text-[10px] font-black p-2 outline-none focus:ring-2 ring-blue-500/20 cursor-pointer"
                  >
                     <option value="2025">2025</option>
                     <option value="2026">2026</option>
                  </select>
               </div>
            </div>
            
            <div className="p-8">
               <Calendar 
                attendanceData={attendanceMap} 
                onDateSelect={handleDateSelect}
               />
            </div>
          </div>
        </div>

        {/* Detail Modal */}
        <AttendanceDetailModal 
          isOpen={isLogModalOpen}
          onClose={() => setIsLogModalOpen(false)}
          date={selectedLogDate}
          record={attendanceMap[selectedLogDate]}
        />
      </div>
    </div>
  );
};

export default Dashboard;
